### ISSUE TITLE
realpath: command not found

### ISSUE THREAD

**Issue by DrJeff** [allejok96/jw-scripts#2]
Ok I'm sure I missed something but how do I define the path/datadir?

I tried this string 
```jw-scripts$ sudo jwb-index --lang=E --quality=240  --download --latest```

and the result is this:
```/usr/local/bin/jwb-index: line 256: realpath: command not found
LatestVideos
./shared-functions: line 318: realpath: command not found
Error in write_to_playlist```

Any ideas of what is happening?
Thanks

**Comment by DrJeff** [comment]
Ok solved it myself! I was not really looking at what was happening I was missing the dependency ```realpath```! I'm running this in a VM of Ubuntu so the solution was ```apt-get install realpath``` yep that easy! :)

**Comment by allejok96** [comment]
Thanks for the feedback! I will add that as a dependency and add a note to the README.  

And normally I wouldn't run it with sudo becasue that is an unnecessary risk, but I'm sure you already knew that

**Comment by DrJeff** [comment]
How do you run this, a complete dump of the VOD main menu? Or individual Categories?

**Comment by allejok96** [comment]
Brief explanation: [mediator.jw.org](http://mediator.jw.org/v1/categories/E/VideoOnDemand) returns JSON data which contain all info about the categories and videos. The script then downloads and parses the JSON file for each category (you see all the codenames in the output of the script).

A bash script is kind of a rough solution since there are languages, like Python, that support parsing JSON, but that's the only way I know!

**Comment by DrJeff** [comment]
Oh I meant how do you keep your own data as a Video On Demand main download of all at first, then run a cron job to update the total.  Or do individual categories like Latest, VODChildren, VODTeenagers, and then update just those via cron jobs. I use plex so I want to download the actual files so I was going the route of the individual category to preserve the space, server load, and time. I have this running on my unRAID server so far I have it working on the main server and adding the files to the shares just beautifully. Can you use multiple ```--category=``` in one command?

**Comment by allejok96** [comment]
No you cannot use multiple categories in a single command. You will have to run the command multiple times. But it's a good idea...

I would do a dump of the categories I want at first, and then run a cron job with `--latest`. The latest videos will be from all categories though.

**Comment by DrJeff** [comment]
Cool thanks! I got it running the way I want, I was hoping that the --latest did that!
