### ISSUE TITLE
UnicodeEncodeError

### ISSUE THREAD

**Issue by jongkok** [allejok96/jw-scripts#21]
Dear Brother

Thank you for your script.
Perhaps you could help with error I experienced:
![image](https://user-images.githubusercontent.com/52023613/66701589-e69bfa00-ed27-11e9-9b93-2d82392ab188.png)

Thank you.

**Comment by jongkok** [comment]
I changed output.py:

def _write_to_m3u(source, name, file):
    """Write entry to a M3U playlist file."""
    _truncate_file(file, string='#EXTM3U\n')
    with open(file, 'a'**, encoding='utf-8'**) as f:
        f.write('#EXTINF:0,' + name + '\n' + source + '\n')

and no more error.

**Comment by allejok96** [comment]
Thanks for bringing my attention to this.

This is the second issue with utf-8 encoding/decoding, and I guess there are probably more in the code.

I'll give it a overlook and try to fix all of them...
