### ISSUE TITLE
Return watching

### ISSUE THREAD

**Issue by marek-dziechciarz** [allejok96/jw-scripts#27]
In KODI addon JW Broadcasting there are function to return watching previously stopped playback.

This is very usefull function when watching long programs like monthly program...

**Comment by allejok96** [comment]
Yes, that's correct. That's a feature that Kodi has. And it _is_ very useful.

You only made a statement. You haven't even asked a question... I can't read your mind.

Is this a feature request, or just praise?

**Comment by marek-dziechciarz** [comment]
Sorry i mean that if that option was also availble in media player for JW broadcasting

**Comment by allejok96** [comment]
Here are the Python scripts I have made:
nwt-index
jwb-index
jwb-stream
jwb-rpi
jwb-import

Please tell me what you refer to when you say "JW broadcasting media player".

**Comment by allejok96** [comment]
Are you using Plex or something? Kodi can be installed on Android, and that way you could use the Kodi add-on (although it would be a ugly solution). I don't know if it works for Android TV though...

**Comment by allejok96** [comment]
Since I don't believe this bug is relevant to the project I'm closing it
