### ISSUE TITLE
List languages

### ISSUE THREAD

**Issue by bergvdna** [allejok96/jw-scripts#28]
Good day,

I am happy with jw-index to find audio files.

Some categories are not language sensitive, but vocally they are.

So I try to find the Dutch version with:

python jwb-index --mode stdout --lang nl --category Audio> C: \ Users \ berga \ Documents \ JWB \ Output \ test

I get an error:

python jwb-index --mode stdout --lang nl --category Audio> C: \ Users \ berga \ Documents \ JWB \ Output \ test

>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
Traceback (most recent call last):
  File "jwb-index", line 34, in <module>
    settings = parser.parse_args ()
  File "C: \ Users \ berga \ Documents \ JWB \ jw-scripts-master \ jwlib \ arguments.py", line 107, in parse_args
    super (). parse_args (* args, namespace = settings, ** kwargs)
  File "C: \ Users \ berga \ AppData \ Local \ Programs \ Python \ Python38 \ lib \ argparse.py", line 1768, in parse_args
    args, argv = self.parse_known_args (args, namespace)
  File "C: \ Users \ berga \ AppData \ Local \ Programs \ Python \ Python38 \ lib \ argparse.py", line 1800, in parse_known_args
    namespace, args = self._parse_known_args (args, namespace)
  File "C: \ Users \ berga \ AppData \ Local \ Programs \ Python \ Python38 \ lib \ argparse.py", line 2006, in _parse_known_args
    start_index = consume_optional (start_index)
  File "C: \ Users \ berga \ AppData \ Local \ Programs \ Python \ Python38 \ lib \ argparse.py", line 1946, in consume_optional
    take_action (action, args, option_string)
  File "C: \ Users \ berga \ AppData \ Local \ Programs \ Python \ Python38 \ lib \ argparse.py", line 1874, in take_action
    action (self, namespace, argument_values, option_string)
  File "C: \ Users \ berga \ Documents \ JWB \ jw-scripts-master \ jwlib \ arguments.py", line 14, in __call__
    result = function (values)
  File "C: \ Users \ berga \ Documents \ JWB \ jw-scripts-master \ jwlib \ arguments.py", line 32, in verify_language
    raise ValueError (code + ': invalid language code')
ValueError: en: invalid language code
<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<

ValueError: en: invalid language code

--lang nl is therefore not good.

But if I search the list of languages ​​with:
python jwb-index --mode stdout --lang nl --category  Audio >C:\Users\berga\Documents\JWB\Output\test

Then I will get output, but not what I expect!

>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
VideoOnDemand (Video Categories)
VODStudio (JW Broadcasting)
VODChildren (Children)
VODTeenagers (Teenagers)
VODFamily (Family)
VODProgramsEvents (Programs and Events)
VODOurActivities (Our Activities)
VODMinistry (Our Meetings and Ministry)
VODOurOrganization (Our Organization)
VODBible (The Bible)
VODMovies (Movies)
VODMusicVideos (Music)
VODIntExp (Interviews and Experiences)
StudioFeatured (Featured Videos)
..............
.............
............
<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<

What am I doing wrong?

I hope to receive an answer soon.

Thank you very much.

Arie van den Berg.

**Comment by allejok96** [comment]
I may have to update the wiki pages, since I've recently made some changes to the script... If you run

     jwb-index --help

you get all the available options. If you're on the latest version, you run `--languages` to get a list of valid language codes. In this case, Dutch is a capital letter O.

I think you've mixed up your error logs somehow. Both commands you give as examples are identical, yet one works and one doesn't. And the error message says `en: invalid language code` even if the command was run with `--lang nl`.

The second example should indeed only show audio categories, but in this case it starts with `VideoOnDemand`. I ran the same, and here's what I got:
```
./jwb-index --mode stdout --category Audio

Audio (Audio)
SJJMeetings (“Sing Out Joyfully”—Meetings)
SJJInstrumental (“Sing Out Joyfully”—Instrumental)
SJJChorus (“Sing Out Joyfully”—Vocals)
Vocal (Sing to Jehovah—Chorus)
AudioOriginalSongs (Original Songs)
AudioChildrenSongs (Children’s Songs)
KingdomMelodies (Kingdom Melodies)
Dramas (Dramas)
DramaticBibleReadings (Dramatic Bible Readings)
```

Please get back to me if you encounter more problems.

**Comment by bergvdna** [comment]
Hi Alex,

You are fantastic.

Everithing works fine.

Thanks for your quick response.

Have a good time.

Greetings,
Arie.

Op za 28 mrt. 2020 16:33 schreef Alex <notifications@github.com>:

**Comment by allejok96** [comment]
Thanks. Glad I could help.
