### ISSUE TITLE
possible to get the friendly name ?

### ISSUE THREAD

**Issue by darkace1998** [allejok96/jw-scripts#30]
Hallo Thanks for the awesome work.

i wanted to ask if it is possible to get the friendly names for the videos as the file name

Thanks for he help 
kind regards 

Julian

**Comment by allejok96** [comment]
You can create links with friendly names:

    jwb-index --mode filesystem --download --latest

Does this work for your use case?

**Comment by darkace1998** [comment]
jwb-index --download --lang=O --quality=720 --mode filesystem  --latest /downloads/

this make a seperate folder with the info but my player only looks at the file names so i would have to rename everything

**Comment by allejok96** [comment]
Fixed. Hope it works...

    jwb-index --download --friendly
