### ISSUE TITLE
Not an Issue: Just a windows example

### ISSUE THREAD

**Issue by pattikay** [allejok96/jw-scripts#37]
Thank you @allejok96 for these scripts and their continual maintenance.
An example below for your consideration - that can be added to wiki for (_windows_) users.

### Download all Monthly broadcasts (Subcategory of VODStudio) in Swahili language from 2019 January to present

`python jwb-index -c StudioMonthlyPrograms --lang=SW -Q 360 --since 2019-01-01 --download C:\Users\User\Videos\JWB`

**Comment by allejok96** [comment]
Thanks for bringing this to my attention. Seems like the important thing here is "python" at the beginning. I started adding it to the wiki, then I tested installation/usage on Windows and realized how complicated and badly supported it is right now, so I'm looking into improving that...

**Comment by allejok96** [comment]
Easy installation on windows now fixed
