### ISSUE TITLE
omxplayer always running

### ISSUE THREAD

**Issue by MDylan** [allejok96/jw-scripts#4]
Hi!

First of all, thank you for this great scripts!
I installed on my rPI the jwb rpi scripts ([based on this](https://github.com/allejok96/jw-scripts/wiki/jwb-rpi)), and I would like to use this to download all videos from tv.jw.org.
Download works ok, but after that, I realized, that omxplayer always running. 
The "now_playing" file updateing in every minutes. 
When I kill omxplayer process, it's restarted immediately. 
It's normal? I would like to use this script to download videos into my plex directory.
Thank you for your help.
David

**Comment by allejok96** [comment]
That is perfectly normal - phew. But if you're using Plex, you should use [jwb-index](https://github.com/allejok96/jw-scripts/wiki/jwb-index) instead.

jwb-rpi works without Plex and plays videos randomly - and in its turn uses jwb-index to download them. It also does some fancy things (read: broken-hacked-together-solution) to monitor disk space and delete old videos. You won't get that with jwb-index. But you probably would be just fine putting jwb-index in your crontab so it updates the latest videos every hour or so (as described in link above).

You will find more options in that link, but maybe something like this would suit you:
`jwb-index --latest --download --mode=filesystem /path/to/video/folder`

The "filesystem" option will organize the videos in folders, similar to what you get when you browse tv.jw.org.

I'll clean up the README and clarify this, as it seems like Plex is what the scripts are mostly used for.
