### ISSUE TITLE
Symlinks are not created correctly

### ISSUE THREAD

**Issue by mh166** [allejok96/jw-scripts#40]
First of all: thank you so much for making it so easy to have an offline copy of all the videos available and easily accessible. :)

Unfortunately, I have a problem with `-m filesystem`: only the two top-level symlinks (for Latest and VoD) are set correctly. Any other symlink is missing "../" in the target, no matter whether it's a video or a folder.

![image](https://user-images.githubusercontent.com/3167596/125050188-0a79a480-e0a2-11eb-93ea-e02434e80614.png)

As you can see, the symlinks always expect the target to be in the same directory when, in reality, they should be pointing to the parent directory.

This is the command that I used to download the video files and generate the directory structure.

```
# python3 ./jwb-index -d --since 2020-01-01 -l X -m filesystem --limit-rate 0 --free 2048 /media/jwb-videos
```

**Comment by allejok96** [comment]
Thanks for the good bug report. I actually have fixed this bug in the beta branch, but I had forgotten about it. When I get the opportunity I will push the fix into the master branch...

**Comment by mh166** [comment]
Thank you for that quick fix! Works great, now! 👍
