### ISSUE TITLE
TypeError on Ubuntu

### ISSUE THREAD

**Issue by mildnl** [allejok96/jw-scripts#5]
I tried to use your programm as it is exactly what I need. Thank you for your work.
Problem is that I dont know much about python so cant help much myself atmo.

When I try to load the jwb-index command as given in your example I get the follwoing error message.
TypeError: the JSON object must be str, not 'bytes'

When I try to run the programm on my windows laptop over an ide it works fine but not through the terminal on ubuntu.

![image](https://cloud.githubusercontent.com/assets/10140809/26603595/a3526f26-4587-11e7-8c7e-8df8a8094789.png)

**Comment by allejok96** [comment]
I've seen that error too, it happens in python 3.5, but not 3.6 which I tested it on originally. This is the first REAL python program I've made, so I'm a bit of a noob myself ;) Naturally I must make it work with 3.5. Will take a look at it soon.

**Comment by allejok96** [comment]
Tested on Python 3.4 and seems to work now.
