### ISSUE TITLE
How to get the jw-scripts to work on Windows 10

### ISSUE THREAD

**Issue by pattikay** [allejok96/jw-scripts#6]
Hi,

Thank you for sharing this scripts.
I would like to share how you can get them to work on a windows machine. I tried on Windows 10 but I am sure this can be adapted for other versions of windows.

Briefly- without many details, these are the steps, I am sure there could be better ways - but this is what worked for me.

1. Create a folder in C drive e.g. C:\JWBroadcast\
2. Install [git ](https://git-scm.com/download/win)( optionally you can install inside the folder in 1. above [posh-git ](https://github.com/dahlbyk/posh-git) )
3. Install python for windows - make sure to add environment variable to python path.
4. Install [simplejson](https://github.com/simplejson/simplejson) inside the folder in 1. above
5.  Install jw-scripts inside the folder in 1. above		
-    You will need to set the Execution policy to allow scripts to be run by admin account
- git clone https://github.com/allejok96/jw-scripts.git
- cd jw-scripts
- run from command prompt / powershell python setup.py install
you can change the working directory in jwb-index "c:**\\\\**JWBroadcast**\\\\**"
6.  Install curl - [download curl ](https://curl.haxx.se/download.html) and copy and unzip the 7/zip file to the folder in 1. above. Rename it to curl
7. Add environment variable path to curl\bin folder in 6 above.
8. open Windows PowerShell or command prompt with admin account (not sure why it didn't work with normal account) 
9. run: jwb-index  --download --category VODChildren
10. run jwb-index --mode html  --download --category VODChildren

I may have missed some steps (especially during the installation process - however these are the general steps I took)
I hope this helps someone out there! 
Thank you allejok96 for these scripts! 🥇 👍

**Comment by allejok96** [comment]
Thanks! As I just wiped my Windows 10 dual-boot :smile:
I've added the instructions to the wiki page, and a link in the README.
