### ISSUE TITLE
Unable to run on MacOS Sierra

### ISSUE THREAD

**Issue by leejk421** [allejok96/jw-scripts#8]
Hi, I installed Python3.6.2 and ran the setup.py with no errors. However when trying to run job-index I get these errors in terminal:

[errors.txt](https://github.com/allejok96/jw-scripts/files/1275501/errors.txt)

Any thoughts?

**Comment by leejk421** [comment]
Found the solution here if others encounter this: https://stackoverflow.com/questions/42098126/mac-osx-python-ssl-sslerror-ssl-certificate-verify-failed-certificate-verify

**Comment by allejok96** [comment]
Thanks for the input. Will add a note to the installation instructions.
