### ISSUE TITLE
NotImpementedError on MacOS Sierra

### ISSUE THREAD

**Issue by leejk421** [allejok96/jw-scripts#9]
Hello,

After running the script and having it download a few videos, I am getting this error, which I assume is at the end of the script's completion?

macmini:jw-scripts-master leejk$ ./jwb-index --latest --download --mode filesystem --free 50000 /Users/leejk/jw_broadcasting
free space: 324526 MiB, minimum limit: 50000 MiB
LatestVideos (Latest Videos)
downloading: jwb_E_201708_11_r720P.mp4 (2016 Puerto Rico Special Convention)
size mismatch, deleting: jwb_E_201708_11_r720P.mp4.part
Traceback (most recent call last):
  File "./jwb-index", line 90, in <module>
    jo.output_filesystem(r, wd, subdir)
  File "/Users/leejk/Downloads/jw-scripts-master/jwlib/output.py", line 130, in output_filesystem
    os.symlink(source, link, dir_fd=dir_fd)
NotImplementedError: dir_fd unavailable on this platform

**Comment by allejok96** [comment]
https://github.com/allejok96/jw-scripts/tree/v1.2-beta

Pull the latest beta and check out if it works. My fault, the code that caused the problem on Mac didn't even do anything!

Just so you realize, `--mode filesystem` isn't needed if you just want to download all videos in a messy bunch. What it does is create a directory structure, and that is were the problem came.

**Comment by leejk421** [comment]
hello,

Although I have not been able to finish a download task yet, to see if all the symlinks get created, I think the error is gone now, but I think there be a separate issue now.  I used this  command to get all videos from July 1rst 2017 until now, but it seems to be downloading everything, even stuff from 2015 & 2016. Did I specify the command wrong?

jwb-index --download --since 2017-07-01 --mode filesystem --free 50000 /Users/leejk/jw_broadcasting

**Comment by allejok96** [comment]
Fixed that too 😊

**Comment by leejk421** [comment]
Ok thank you! It is fixed now.
